CREATE TABLE IF NOT EXISTS users (
  line_id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL DEFAULT 'Unknown',
  coins BIGINT NOT NULL DEFAULT 0,
  message_count BIGINT NOT NULL DEFAULT 0,
  login_streak INTEGER NOT NULL DEFAULT 0,
  last_login_date DATE,
  ai_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admins (
  line_id TEXT PRIMARY KEY,
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rob_history (
  id BIGSERIAL PRIMARY KEY,
  robber_id TEXT NOT NULL,
  target_id TEXT NOT NULL,
  success BOOLEAN NOT NULL,
  amount BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
